name: Bump Version (reusable)

on:
  workflow_call:
    inputs:
      NX_BASE:
        required: true
        type: string
      NX_HEAD:
        required: true
        type: string

env:
  cache-name: cache-node-modules
  NX_BASE: ${{ secrets.NX_BASE }}
  NX_HEAD: ${{ inputs.NX_HEAD }}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-${{ env.cache-name }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          workflow-id: ci-cd.yaml

      - name: git config
        run: |
          git config user.name "automated-version-bump"
          git config user.email "automated-version-bump@users.noreply.github.com"

      - name: Bump version (automatic)
        run: |
          export HUSKY=0
          npx nx affected \
          --target=version \
          --push
